In [4]:
import numpy as np


In [5]:
a = np.array([[1,5,9],[8,5,6]],dtype='int64')
print (a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)
print(a[0][1])
print(a[0][-1])
print(a[:,2])


[[1 5 9]
 [8 5 6]]
2
(2, 3)
int64
8
5
9
[9 6]


In [6]:
a = np.array([[1,2,3,4,5,6],[7,8,9,4,5,6]])
print(a)
print(a[:,0:6:2])


[[1 2 3 4 5 6]
 [7 8 9 4 5 6]]
[[1 3 5]
 [7 9 5]]


In [7]:
# 2D array
a = np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,4,1,2,3,6,5]])
print(a[0,:]) # print a specific row
print(a[:,0]) # print a specific column
a[1,-3] = 10  # change the value 
a[0,0:-1:3] = 0
print(a)
print(a[0,0:-1:2])

[1 2 3 4 5 6 7 8 9]
[1 9]
[[ 0  2  3  0  5  6  0  8  9]
 [ 9  8  7  4  1  2 10  6  5]]
[0 3 5 0]


In [8]:
a = np.array([[[1,2,3],[4,5,6]],[[7,5,3],[1,0,9]]
])
print(a)
print(a[0][0][0])
print(a[1,0,1])

[[[1 2 3]
  [4 5 6]]

 [[7 5 3]
  [1 0 9]]]
1
5


In [9]:
# special arrays
print(np.zeros((3,3,3),dtype='int32'))
print('\n')
print(np.ones((3,3,3),dtype='int32'))
print('\n')
print(np.identity(4, dtype='int32') )
print('\n')
print(np.full((3,3),15,dtype= 'int32'))


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


[[15 15 15]
 [15 15 15]
 [15 15 15]]


In [10]:
print(np.random.rand(4,2))
print(np.random.randint(1,7, size = (3,3)))


[[0.91427356 0.02827276]
 [0.59810925 0.80080977]
 [0.49740771 0.44501157]
 [0.7141878  0.06725709]]
[[1 3 4]
 [5 4 3]
 [4 3 5]]


In [11]:
a = np.ones((5,5),dtype='int32')
a[1,1:-1] = 0
a[3,1:-1] = 0
a[1:-1,1:-1]=0
a[2][2]=9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [12]:
a = np.ones((5,5),dtype='int32')
b = np.zeros((3,3),dtype='int32')
b[1,1] = 9
a[1:-1,1:-1] = b
print(b)
print('\n')
print(a)


[[0 0 0]
 [0 9 0]
 [0 0 0]]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])
b = a.copy()
b[1,1] = 0
print(a)
print('\n')
print(b)


[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 0 6]]


In [14]:
a = np.array([1,2,3,4,5,6,7,8,9])

print(a)

[1 2 3 4 5 6 7 8 9]


In [15]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
a ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [17]:
b = np.sin(a)
c = np.tan(a)
d = np.sin(a)
print(b,'\n')
print(c,'\n')
print(d,'\n')

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849] 

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566] 

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849] 



In [18]:
#linear algebra 
a = np.ones((2,3),dtype = 'int32')
b = np.full((3,4),15)
np.matmul(a,b)

array([[45, 45, 45, 45],
       [45, 45, 45, 45]])

In [19]:
a = np.array([[1,2,9],[4,5,6]])
print(np.min(a))
print(np.max(a))
print(np.sum(a))

1
9
27


In [20]:
print(np.max(a,axis = 0)) # max in each culomn
print(np.max(a,axis = 1)) # max in each row

[4 5 9]
[9 6]


In [21]:
# array stacking 
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([6,7,8,3,4,5,1,2,9])
c = np.array([8,3,4,5,1,2,6,7,9])
print(np.vstack((a,b,c)))
print('\n')
print(np.hstack((c,a,b)))



[[1 2 3 4 5 6 7 8 9]
 [6 7 8 3 4 5 1 2 9]
 [8 3 4 5 1 2 6 7 9]]


[8 3 4 5 1 2 6 7 9 1 2 3 4 5 6 7 8 9 6 7 8 3 4 5 1 2 9]


In [22]:
# loading data from a text file using 
data = np.genfromtxt('data.txt',delimiter = ',')
print(data.astype('int'))


[[  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  1  13  21  11 196  75

In [23]:
print(data > 20)

[[False  True  True False  True False False False  True False False False
  False False False False  True  True]
 [False False  True False  True  True False False  True False False False
  False False False False False False]
 [False  True False  True  True  True False  True False False False False
  False False False False False False]
 [False  True  True False  True False False False  True False False False
  False False False False  True  True]
 [False False  True False  True  True False False  True False False False
  False False False False False False]
 [False  True False  True  True  True False  True False False False False
  False False False False False False]
 [False  True  True False  True False False False  True False False False
  False False False False  True  True]
 [False False  True False  True  True False False  True False False False
  False False False False False False]
 [False  True False  True  True  True False  True False False False False
  False False False Fa

In [34]:
print(data[data > 50 ])

[999.  78.  76.  88. 196.  75. 766.  75.  55. 999.  78.  76.  88. 196.
  75. 766.  75.  55. 999.  78.  76.  88. 196.  75. 766.  75.  55. 999.
  78.  76.  88. 196.  75. 766.  75.  55. 999.  78.  76.  88. 196.  75.]


In [25]:
a = np.array([[1,4,7,8,5,2,3,6,9],[7,8,5,1,4,2,3,6,9]])
print(a[1,:])
b = np.array([7,8,5,1,4,2,3,6,9])
print(b[[1,2,3]])


[7 8 5 1 4 2 3 6 9]
[8 5 1]


In [26]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30]
            ])
print(a[2:4,0:2])
print('\n')
print(a[[0,1,2,3],[1,2,3,4]])

[[11 12]
 [16 17]]


[ 2  8 14 20]
